### ISSUE TITLE
Error in plugin "gulp-fill-pot-po": Only Vinyl objects can be transformed

### ISSUE THREAD

**Issue by yochananmarqos** [yilozt/rounded-window-corners#101]
Building from fdc27e6 running `yarn install && yarn build`:

```
08:24:47] Finished 'gen_pot' after 53 ms
[08:24:47] Starting 'fill_pot'...
[08:24:47] 'fill_pot' errored after 4.14 ms
[08:24:47] Error in plugin "gulp-fill-pot-po"
Message:
    Only Vinyl objects can be transformed.
[08:24:47] 'build' errored after 18 s
error Command failed with exit code 1.
```

<details>
<summary>full log</summary>

```
yarn install v1.22.19
info No lockfile found.
[1/4] Resolving packages...
warning gulp > glob-watcher > chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
warning gulp > glob-watcher > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning gulp > glob-watcher > anymatch > micromatch > snapdragon > source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
warning gulp > glob-watcher > anymatch > micromatch > snapdragon > source-map-resolve > source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
warning gulp > glob-watcher > anymatch > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning gulp > glob-watcher > anymatch > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning gulp-potomo > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 15.09s.
yarn run v1.22.19
$ gulp build
[15:32:42] Using gulpfile ~/gnome-shell-extension-rounded-window-corners-git/src/rounded-window-corners/gulpfile.js
[15:32:42] Starting 'build'...
[15:32:42] Starting '<anonymous>'...
[15:32:42] Finished '<anonymous>' after 611 μs
[15:32:42] Starting 'generate_gi_ext'...
[15:32:42] Starting 'generate_gi_prefs'...
Try to detect detect version of gnome-shell
Gnome-shell version:  11
Generate .d.ts files for preferences pages: 
Loading docs.json...
Finding GIR files...
Resolving libraries...
Loading GIR files...
Adding generics...
Injecting types...
Generated!

[15:32:48] Finished 'generate_gi_prefs' after 6.58 s
Generate .d.ts files for extensions: 
Loading docs.json...
Finding GIR files...
Resolving libraries...
Loading GIR files...
Adding generics...
Unknown type:  {
    "name": "gpu",
    "transfer-ownership": "none"
} 
Marking as unknown!
Unknown type:  {
    "name": "logical_monitor",
    "transfer-ownership": "none"
} 
Marking as unknown!
Injecting types...
>> Conflict in Text.position with Actor.position.
>> Conflict in Text.position with Actor.position.
Generated!

The following types were prefixed with __ to preserve valid JavaScript identifiers.
NM.__80211Mode = NM.80211Mode
NM.__80211ApFlags = NM.80211ApFlags
NM.__80211ApSecurityFlags = NM.80211ApSecurityFlags

[15:32:49] Finished 'generate_gi_ext' after 7.1 s
[15:32:49] Starting 'rename_gi'...
[15:32:49] Finished 'rename_gi' after 68 ms
[15:32:49] Starting '<anonymous>'...
[15:32:49] Finished '<anonymous>' after 891 μs
[15:32:49] Starting 'format'...
[15:32:50] Finished 'format' after 1.46 s
[15:32:50] Starting 'compile_ts'...
[15:32:52] Finished 'compile_ts' after 1.96 s
[15:32:52] Starting 'copy_resources'...
[15:32:52] Finished 'copy_resources' after 2.88 ms
[15:32:52] Starting 'compile_schema'...
[15:32:52] Finished 'compile_schema' after 18 ms
[15:32:52] Starting 'gen_pot'...

  59 messages extracted
  -----------------------------
  67 total usages
  33 files (12 with messages)
   1 message context (default)

[15:32:52] Finished 'gen_pot' after 52 ms
[15:32:52] Starting 'fill_pot'...
[15:32:52] 'fill_pot' errored after 2.58 ms
[15:32:52] Error in plugin "gulp-fill-pot-po"
Message:
    Only Vinyl objects can be transformed.
[15:32:52] 'build' errored after 11 s
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

</details>

**Comment by emansom** [comment]
Experiencing this as well, when building the AUR git package.

**Comment by yochananmarqos** [comment]
@yilozt Any ideas here? No one is able to install or update the AUR packages due to this.

**Comment by kypello** [comment]
seems to have been fixed, I just installed it from AUR without issues

**Comment by yochananmarqos** [comment]
@kypello It's not fixed, I just [worked around it ](https://aur.archlinux.org/cgit/aur.git/commit/?h=gnome-shell-extension-rounded-window-corners&id=a1f52e1736aed52a48ebb52284f608873cd8a24e)by skipping the `fill_pot` step for now.url

**Comment by yochananmarqos** [comment]
The issue is resolved with the latest commits.
